pathJsonTemplate: 'pccLspIetfTemplate.json'
pathNamePrefix: 'pccLspIetfCloneTest'
profileId: 1
pathQty: 2
groupIdFrom: 60
destinationAddressIpv4: '1.1.1.2'
sourceAddressIpv4: '1.1.1.1'
sourceRouterAddressIpv4: '1.1.1.1'
bootstrapServers: '10.2.16.11:9192'  # Requires port too
topic: 'ns-eg-5685c381-dc69-4d75-a2b7-c21420386740'
partition: '0'
sslCaLocation: 'truststore.pem'
period: 60 #seconds
upThreshold: '90000' # aggregate-octets-periodic
upOccurrences: 2
downThreshold: '1000'
downOccurrences: 4
